# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "uas" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Grub config
  boot.loader.grub.enable = true;
  boot.loader.grub.version = 2;
  boot.loader.grub.efiSupport = true;
  boot.loader.grub.efiInstallAsRemovable = true;
  boot.loader.grub.device = "nodev";
  # boot.loader.grub.device = "/dev/disk/by-id/usb-JMicron_Tech_DD201909040039-0:0";

  # EFI
  # boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = false;
  boot.loader.efi.efiSysMountPoint = "/boot/efi";

  # Plymouth boot splash screen
  boot.plymouth.enable = true;
  boot.plymouth.themePackages = with pkgs; [ libsForQt5.breeze-plymouth ];
  boot.plymouth.theme = "breeze";


  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d63e5823-45e4-40b4-93d7-57dd35c75e8c";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=lzo" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/d63e5823-45e4-40b4-93d7-57dd35c75e8c";
      fsType = "btrfs";
      options = [ "subvol=@boot" "compress=lzo" "noatime" ];
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/3874-9AD5";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/d63e5823-45e4-40b4-93d7-57dd35c75e8c";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=lzo" "noatime" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/d63e5823-45e4-40b4-93d7-57dd35c75e8c";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=lzo" "noatime" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/0792a4ca-f953-40d3-9933-97f7b0b41401"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
